<a href="https://colab.research.google.com/github/Klnishant/ActivationFunctionAssignment/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import joblib
import matplotlib.pyplot as plt
import pandas as pd

In [30]:
class Perceptron:
  def __init__(self,eta,epochs):
    self.weights = np.random.randn(3)*1e-4
    print(f"self.weights:{self.weights}")
    self.eta=eta
    self.epochs=epochs
  def activationFunction(self,inputs,weights):
    z=np.dot(inputs,weights)
    return np.where(z>0,1,0)
  def fit(self,x,y):
    self.x=x
    self.y=y
    x_with_bias=np.c_[self.x,-np.ones((len(self.x),1))]
    print(f"x_with_bias:\n{x_with_bias}")
    for epoch in range(self.epochs):
      print(f"for epoch:{epoch}")
      y_hat=self.activationFunction(x_with_bias,self.weights)
      print(f"predicted value:\n{y_hat}")
      error = self.y-y_hat
      print(f"error:{error}")
      self.weights=self.weights + self.eta*np.dot(x_with_bias.T,error)
      print(f"new weight:{self.weights}")
  def predict(self,x):
    x_with_bias = np.c_[self.x,-np.ones((len(self.x),1))]
    return self.activationFunction(x_with_bias,self.weights)

In [18]:
Perceptron(0.5,5)

self.weights:[ 1.21717163e-04  1.02096301e-04 -3.94110092e-06]


In [31]:
data = {"x1":[0,0,1,1],"x2":[0,1,0,1],"y":[0,0,0,1]}
AND = pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [32]:
x=AND.drop("y",axis=1)
x

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [33]:
y=AND["y"]
y.to_frame()

y
0  0
1  0
2  0
3  1

In [34]:
model = Perceptron(0.5,10)
model.fit(x,y)

self.weights:[-7.83478201e-05 -1.12236684e-04  2.06312971e-05]
x_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch:0
predicted value:
[0 0 0 0]
error:0    0
1    0
2    0
3    1
Name: y, dtype: int64
new weight:[ 0.49992165  0.49988776 -0.49997937]
for epoch:1
predicted value:
[1 1 1 1]
error:0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
new weight:[-7.83478201e-05 -1.12236684e-04  1.00002063e+00]
for epoch:2
predicted value:
[0 0 0 0]
error:0    0
1    0
2    0
3    1
Name: y, dtype: int64
new weight:[0.49992165 0.49988776 0.50002063]
for epoch:3
predicted value:
[0 0 0 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
new weight:[0.49992165 0.49988776 0.50002063]
for epoch:4
predicted value:
[0 0 0 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
new weight:[0.49992165 0.49988776 0.50002063]
for epoch:5
predicted value:
[0 0 0 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
new weight:[0.49992165 0.49988776 0.50002063]

In [35]:
model.predict(x)

array([0, 0, 0, 1])