<a href="https://colab.research.google.com/github/Klnishant/ActivationFunctionAssignment/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
t2=torch.tensor([4.,5,6,7])
t2

tensor([4., 5., 6., 7.])

In [5]:
t3 = torch.tensor([[1.,2],
                   [3,4],
                   [5,6]])
t3

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [6]:
print(t1.shape)
print(t2.shape)
print(t3.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])


In [8]:
x=torch.tensor(3.)
w=torch.tensor(4.,requires_grad=True)
b=torch.tensor(5.,requires_grad=True)

x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [9]:
y=w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [10]:
y.backward()

In [11]:
print("dy/dx:",x.grad)
print("dy/dw:",w.grad)
print("dy/db:",b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [12]:
t6 = torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [14]:
t7 = torch.cat((t3,t6))
t7

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [15]:
t8 = torch.sin((t7))
t8

tensor([[ 0.8415,  0.9093],
        [ 0.1411, -0.7568],
        [-0.9589, -0.2794],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [16]:
t9 = t8.reshape((3,2,2))
t9

tensor([[[ 0.8415,  0.9093],
         [ 0.1411, -0.7568]],

        [[-0.9589, -0.2794],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [17]:
import numpy as np

In [19]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [20]:
y=torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [21]:
x.dtype,y.dtype

(dtype('int64'), torch.int64)

In [23]:
z=y.numpy()
z

array([[1, 2],
       [3, 4]])

In [28]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [29]:
target = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [30]:
inputs = torch.from_numpy(inputs)
target=torch.from_numpy(target)

print(inputs,"\n")
print(target)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) 

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [31]:
w=torch.randn((2,3),requires_grad=True)
b=torch.randn((2,),requires_grad=True)

print(w)
print(b)

tensor([[ 0.0472,  0.6283,  1.3675],
        [ 0.0493, -1.2936, -0.3631]], requires_grad=True)
tensor([ 0.6936, -0.9559], requires_grad=True)


In [32]:
def model(x):
  return x @ w.t() + b

In [33]:
preds = model(inputs)
print(preds)

tensor([[ 105.0339,  -99.6419],
        [ 147.7939, -133.5456],
        [ 168.3027, -191.0677],
        [  83.1175,  -64.9884],
        [ 159.9875, -147.1572]], grad_fn=<AddBackward0>)


In [34]:
print(target)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [35]:
def MSE(actual,target):
  diff=actual-target
  return torch.sum(diff*diff)/diff.numel()

In [36]:
loss = MSE(target,preds)
loss

tensor(28633.0586, grad_fn=<DivBackward0>)

In [37]:
loss.backward()

In [38]:
print(w,"\n")
print(w.grad)

tensor([[ 0.0472,  0.6283,  1.3675],
        [ 0.0493, -1.2936, -0.3631]], requires_grad=True) 

tensor([[  4822.6333,   4773.7080,   3098.6582],
        [-18137.8125, -21073.5352, -12701.2041]])


In [39]:
print(b,"\n")
print(b.grad)

tensor([ 0.6936, -0.9559], requires_grad=True) 

tensor([  56.6471, -219.2802])


In [40]:
w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [41]:
preds=model(inputs)
print(preds)

tensor([[ 105.0339,  -99.6419],
        [ 147.7939, -133.5456],
        [ 168.3027, -191.0677],
        [  83.1175,  -64.9884],
        [ 159.9875, -147.1572]], grad_fn=<AddBackward0>)


In [42]:
loss = MSE(target,preds)
print(loss)

tensor(28633.0586, grad_fn=<DivBackward0>)


In [43]:
loss.backward()

print(w.grad,"\n")
print(b.grad)

tensor([[  4822.6333,   4773.7080,   3098.6582],
        [-18137.8125, -21073.5352, -12701.2041]]) 

tensor([  56.6471, -219.2802])


In [44]:
with torch.no_grad():
  w -= w.grad*1e-5
  b -= b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()

In [45]:
print(w)
print(b)

tensor([[-1.0631e-03,  5.8057e-01,  1.3365e+00],
        [ 2.3066e-01, -1.0828e+00, -2.3613e-01]], requires_grad=True)
tensor([ 0.6930, -0.9538], requires_grad=True)


In [46]:
preds=model(inputs)
loss=MSE(target,preds)
print(loss)

tensor(19617.6250, grad_fn=<DivBackward0>)


In [47]:
for i in range(400):
  preds=model(inputs)
  loss=MSE(target,preds)
  loss.backward()

  with torch.no_grad():
    w -= w.grad*1e-5
    b -= b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

  print(f"epochs:{i/100} and loss:{loss}")

epochs:0.0 and loss:19617.625
epochs:0.01 and loss:13538.2861328125
epochs:0.02 and loss:9437.587890625
epochs:0.03 and loss:6670.31787109375
epochs:0.04 and loss:4801.67236328125
epochs:0.05 and loss:3538.64599609375
epochs:0.06 and loss:2683.78564453125
epochs:0.07 and loss:2104.029296875
epochs:0.08 and loss:1709.707763671875
epochs:0.09 and loss:1440.3935546875
epochs:0.1 and loss:1255.3656005859375
epochs:0.11 and loss:1127.18115234375
epochs:0.12 and loss:1037.3465576171875
epochs:0.13 and loss:973.3990478515625
epochs:0.14 and loss:926.9390869140625
epochs:0.15 and loss:892.30615234375
epochs:0.16 and loss:865.6853637695312
epochs:0.17 and loss:844.5046997070312
epochs:0.18 and loss:827.0311279296875
epochs:0.19 and loss:812.0958251953125
epochs:0.2 and loss:798.9107055664062
epochs:0.21 and loss:786.9442138671875
epochs:0.22 and loss:775.8377685546875
epochs:0.23 and loss:765.3491821289062
epochs:0.24 and loss:755.3145141601562
epochs:0.25 and loss:745.623291015625
epochs:0.26 

In [48]:
preds=model(inputs)
loss=MSE(target,preds)
print(loss)

tensor(19.9107, grad_fn=<DivBackward0>)


In [49]:
from math import sqrt
print(sqrt(loss))

4.462144571462891


In [50]:
preds

tensor([[ 57.2099,  71.4850],
        [ 85.1648,  99.2918],
        [111.8961, 134.1999],
        [ 20.9686,  44.5562],
        [107.2675, 112.1517]], grad_fn=<AddBackward0>)

In [51]:
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [52]:
!nvidia-smi

Mon Apr 29 17:00:44 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [53]:
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor,Lambda,Compose
import matplotlib.pyplot as plt

In [55]:
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

100%|██████████| 26421880/26421880 [00:01<00:00, 16215706.41it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 274651.75it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:00<00:00, 5109299.23it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 4984366.80it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [56]:
type(training_data)

torchvision.datasets.mnist.FashionMNIST

In [57]:
batch_size=64

train_dataloader = DataLoader(training_data,batch_size)
test_dataloader = DataLoader(test_data,batch_size)

for x,y in test_dataloader:
  print("Shape of X[N,C,H,W]:",x.shape)
  print("shape of y",y.shape,y.dtype)
  print(x)
  print(y)
  break

Shape of X[N,C,H,W]: torch.Size([64, 1, 28, 28])
shape of y torch.Size([64]) torch.int64
tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          ...,
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.]]],


        ...,


        [[[0., 0., 0.,  ..., 0., 0., 0.],
          [0., 0., 0.,  ..., 0., 0., 0.],

In [58]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device:{device}")

device:cuda


In [74]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork,self).__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
        nn.Linear(28*28,512),
        nn.ReLU(),
        nn.Linear(512,512),
        nn.ReLU(),
        nn.Linear(512,10)
    )
  def forward(self,x):
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits

model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [75]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(),lr=1e-3)

In [76]:
def train(dataloader,model,loss_fn,optimizer):
  size=len(dataloader.dataset)
  model.train()
  for batch,(X,y) in enumerate(dataloader):
    X,y = X.to(device),y.to(device)

    pred = model(X)
    loss = loss_fn(pred,y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if batch % 100 == 0:
      loss,current = loss.item(), batch*len(X)
      print(f"loss:{loss:>7f} [{current:>5d}/{size:>5d}]")

In [77]:
def test(dataloader,model,loss_fn):
  size = len(dataloader.dataset)
  num_batches = len(dataloader)
  model.eval()
  test_loss, correct = 0, 0
  with torch.no_grad():
      for X, y in dataloader:
          X, y = X.to(device), y.to(device)
          pred = model(X)
          test_loss += loss_fn(pred, y).item()
          correct += (pred.argmax(1) == y).type(torch.float).sum().item()
  test_loss /= num_batches
  correct /= size
  print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [78]:
epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss:2.303403 [    0/60000]
loss:2.291225 [ 6400/60000]
loss:2.273651 [12800/60000]
loss:2.263516 [19200/60000]
loss:2.257194 [25600/60000]
loss:2.223367 [32000/60000]
loss:2.235227 [38400/60000]
loss:2.200183 [44800/60000]
loss:2.201983 [51200/60000]
loss:2.174620 [57600/60000]
Test Error: 
 Accuracy: 44.5%, Avg loss: 2.166714 

Epoch 2
-------------------------------
loss:2.177829 [    0/60000]
loss:2.170161 [ 6400/60000]
loss:2.117217 [12800/60000]
loss:2.128741 [19200/60000]
loss:2.084393 [25600/60000]
loss:2.030281 [32000/60000]
loss:2.060918 [38400/60000]
loss:1.982730 [44800/60000]
loss:1.996381 [51200/60000]
loss:1.937062 [57600/60000]
Test Error: 
 Accuracy: 52.3%, Avg loss: 1.922513 

Epoch 3
-------------------------------
loss:1.951904 [    0/60000]
loss:1.924667 [ 6400/60000]
loss:1.815968 [12800/60000]
loss:1.853741 [19200/60000]
loss:1.741420 [25600/60000]
loss:1.699743 [32000/60000]
loss:1.725519 [38400/60000]
loss:1.617359 [44800

In [79]:
#save model
torch.save(model.state_dict(), "model.pth")
print("Saved PyTorch Model State to model.pth")

Saved PyTorch Model State to model.pth


In [80]:
model = NeuralNetwork()
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>

In [81]:
classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot",
]

model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
    pred = model(x)
    predicted, actual = classes[pred[0].argmax(0)], classes[y]
    print(f'Predicted: "{predicted}", Actual: "{actual}"')

Predicted: "Ankle boot", Actual: "Ankle boot"
