<a href="https://colab.research.google.com/github/Klnishant/ActivationFunctionAssignment/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print(f"Tensorflpw version:{tf.__version__}")
print(f"Eager Execution is:{tf.executing_eagerly()}")

Tensorflpw version:2.15.0
Eager Execution is:True


In [3]:
if tf.test.is_gpu_available():
  print("GPU are available")
else:
  print("CPU are available")

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


GPU are available


In [4]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
tf.config.list_physical_devices("CPU")

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [6]:
inueron = tf.constant(42)
inueron

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [7]:
ineuron1 = tf.constant(1,dtype=tf.int64)
ineuron1

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [8]:
ineuron2 = tf.constant([[4,2],[6,5]])
print(ineuron2)

tf.Tensor(
[[4 2]
 [6 5]], shape=(2, 2), dtype=int32)


In [9]:
inueron.numpy()

42

In [10]:
ineuron2.numpy()

array([[4, 2],
       [6, 5]], dtype=int32)

In [11]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [12]:
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [13]:
const1=tf.constant([[1,2,3],[1,2,3]])
const2=tf.constant([[3,4,5],[3,4,5]])
const_add=tf.add(const1,const2)
const_add

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 6, 8],
       [4, 6, 8]], dtype=int32)>

In [14]:
tf.random.normal(shape=(2,2),mean=0,stddev=0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [15]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.1103168 , 0.7177055 ],
       [0.96924305, 2.667942  ]], dtype=float32)>

In [16]:
var_reassign=tf.Variable(53)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=53>

In [17]:
var_reassign.assign(98)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=98>

In [18]:
initial_value=tf.random.normal(shape=(2,2))
a=tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.66195476, -0.8790444 ],
       [ 0.9812811 ,  0.8194156 ]], dtype=float32)>


In [19]:
new_value = tf.random.normal(shape=(2,2))
a.assign(new_value)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[-0.31368297,  0.46848366],
       [-0.5200199 , -1.0872337 ]], dtype=float32)>

In [20]:
for i in range(2):
  for j in range(2):
    assert a[i][j]==new_value[i][j]

In [27]:
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.48367897,  1.8744891 ],
       [ 1.007245  , -0.53124136]], dtype=float32)>


In [21]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[-0.4368971,  2.3348355],
       [-1.5177884, -0.9348278]], dtype=float32)>

In [22]:
for i in range(2):
  for j in range(2):
    assert a[i][j] == new_value[i][j]+added_value[i][j]

In [23]:
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.4368971,  2.3348355],
       [-1.5177884, -0.9348278]], dtype=float32)>


In [24]:
tensor = tf.Variable([[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]])

In [25]:
tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [26]:
tensor.shape

TensorShape([2, 3])

In [27]:
tensor1=tf.reshape(tensor,[2,3])
tensor2=tf.reshape(tensor,[1,6])

In [28]:
tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [29]:
tensor2

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>

In [30]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))
c=a+b
d=tf.square(c)
e=tf.exp(c)

print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[-0.31702033  0.4934499 ]
 [ 0.79350287  0.46233347]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.64451355 -0.23926863]
 [-0.54350483 -1.7571173 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.32749322  0.25418127]
 [ 0.24999803 -1.2947838 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.10725181 0.06460812]
 [0.06249902 1.6764652 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.3874856  1.2894056 ]
 [1.2840229  0.27395707]], shape=(2, 2), dtype=float32)


In [31]:
tensor*tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [32]:
tensor4 = tensor*4

In [33]:
tensor4

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4,  8, 12],
       [16, 20, 24]], dtype=int32)>

In [34]:
matrix_u=tf.constant([[3,4,3]])
matrix_v=tf.constant([[1,2,1]])
matrix_mult=tf.matmul(matrix_u,tf.transpose(a=matrix_v))

In [35]:
matrix_mult

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

In [36]:
tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [37]:
i=tf.cast(tensor1,dtype=tf.int64)
i

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [38]:
j = tf.cast(tf.constant(4.9),dtype=tf.int32)

In [55]:
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [39]:
ragged=tf.ragged.constant([[1,2,3,4],[],[3,4,5],[1,2,3,4,5],[1,2],[8]])

print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[1, 2, 3, 4], [], [3, 4, 5], [1, 2, 3, 4, 5], [1, 2], [8]]>
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [40]:
var_x=[1,3,7,5,11]
var_y=5
varz = tf.math.squared_difference(var_x,var_y)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  4,  0, 36], dtype=int32)>

In [41]:
numbers = tf.constant([[4.,5.],[7.,3.]])

In [42]:
tf.reduce_mean(input_tensor=numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

In [43]:
tf.reduce_mean(input_tensor=numbers,axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

In [44]:
tf.reduce_mean(input_tensor=numbers,axis=0,keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>

In [45]:
tf.reduce_mean(input_tensor=numbers,axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

In [46]:
tf.reduce_mean(input_tensor=numbers,axis=1,keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[4.5],
       [5. ]], dtype=float32)>

In [52]:
dice1 = tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
dice_sum = dice1+dice2
resulting_matrix = tf.concat(values=[dice1,dice2,dice_sum],axis=1)
print(resulting_matrix)

tf.Tensor(
[[ 4  6 10]
 [ 3  1  4]
 [ 5  5 10]
 [ 3  1  4]
 [ 2  6  8]
 [ 1  6  7]
 [ 3  3  6]
 [ 6  5 11]
 [ 2  6  8]
 [ 6  5 11]], shape=(10, 3), dtype=int32)


In [53]:
t5 = tf.constant([2,11,5,42,7,19,-6,-11,29])
print(t5)

tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)


In [55]:
i=tf.argmax(input=t5)
print(i)
j=tf.argmin(input=t5)
print(j)

t6 = tf.reshape(tensor=t5,shape=(3,3))
print(t6)

min_val1= tf.argmin(input=t6, axis=1)
print(f"min value across column:{min_val1}")
max_val1 = tf.argmax(input=t6,axis=1)
print(f"Maximum value across column:{max_val1}")
min_val2=tf.argmin(input=t6, axis=0)
print(f"minimum value across row:{min_val2}")
max_val2 = tf.argmax(input=t6,axis=0)
print(f"maximum value across row:{max_val2}")

tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
min value across column:[0 1 1]
Maximum value across column:[1 0 2]
minimum value across row:[2 2 0]
maximum value across row:[1 0 2]


In [56]:
variable = tf.Variable([[1,3,5,7],[11,13,17,19]])
checkpoint = tf.train.Checkpoint(var=variable)
save_path = checkpoint.save("./vars")
variable.assign([[0,0,0,0],[0,0,0,0]])
checkpoint.restore(save_path)
print(variable.numpy())

[[ 1  3  5  7]
 [11 13 17 19]]


In [57]:
def f1(x,y):
  return tf.reduce_mean(input_tensor=tf.multiply(x**2,5)+y**2)
f2 = tf.function(f1)
x=tf.constant([4.,-5.])
y=tf.constant([2.,3.])

assert f1(x,y).numpy() == f2(x,y).numpy()

In [58]:
mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_tes) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step
